from ..domain import ReviewResult, Severity


class Renderer:
    def to_json(self, result: ReviewResult) -> str:
        return result.model_dump_json(indent=2)

    def to_markdown(self, result: ReviewResult) -> str:
        md = "# AI Code Review\n\n"
        md += f"**Decision**: {result.decision}\n\n"
        md += f"{result.summary}\n\n"

        if result.stats:
            md += "## Statistics\n"
            for k, v in result.stats.items():
                md += f"- **{k}**: {v}\n"
            md += "\n"

        if result.issues:
            md += "## Issues\n"
            # Group by Severity
            by_severity = {s: [] for s in Severity}
            for issue in result.issues:
                by_severity[issue.severity].append(issue)

            for severity, issues in by_severity.items():
                if not issues:
                    continue
                md += f"### {severity.value}\n"
                for issue in issues:
                    md += f"- **{issue.path}**:{issue.line_start}\n"
                    md += f"  - **{issue.title}**: {issue.message}\n"
                    if issue.suggestion:
                        md += f"  - *Suggestion*: `{issue.suggestion}`\n"

        return md

    def to_github_summary(self, result: ReviewResult, risk_score: int) -> str:
        """
        Compact summary for PR comment.
        """
        icon = (
            "✅"
            if result.decision == "PASS"
            else ("⚠️" if result.decision == "WARN" else "🚫")
        )

        md = f"## {icon} AI Review: {result.decision}\n\n"
        md += f"**Risk Score**: {risk_score}/100\n\n"
        md += f"{result.summary}\n\n"

        if result.issues:
            md += "### Top Issues\n"
            top_issues = [
                i
                for i in result.issues
                if i.severity in (Severity.BLOCKER, Severity.IMPORTANT)
            ][:5]
            if not top_issues:
                top_issues = result.issues[:3]

            for issue in top_issues:
                link = f"{issue.path}#L{issue.line_start}"
                md += (
                    f"- [{issue.path}]({link}): **{issue.title}** "
                    f"({issue.severity.value})\n"
                )

        md += "\n---\n*Generated by AI Code Reviewer*"
        return md
